#!/usr/bin/env python3
"""
Generate the REST API reference for the agentregistry website.

Copies the product repo's openapi.yaml into assets/ and writes a page that
renders it with docs-theme-extras' `openapi` shortcode (Swagger UI).

The spec is copied rather than fetched from GitHub at build time. `src` resolves
through Hugo's `resources.Get`, so the spec is served from the site's own origin
— the page then renders on a runner with no network access, and the shortcode's
build-time parse (which supplies the Copy-as-Markdown summary, since Swagger UI
renders client-side and would otherwise leave that copy empty) cannot be broken
by a slow or unreachable raw.githubusercontent.com.

openapi.yaml is generated upstream by `make gen-openapi` and guarded by
`make verify`, so it is already trustworthy at any commit on main.

Usage (from the workflow, or locally):
  AGENTREGISTRY_DIR=/path/to/agentregistry \\
  WEBSITE_DIR=/path/to/website \\
  python3 scripts/generate-api-ref.py
"""

import os
import shutil
from pathlib import Path

SPEC_SOURCE = Path("openapi.yaml")
SPEC_TARGET = Path("assets") / "ar-docs" / "openapi.yaml"
OUTPUT_PATH = Path("content") / "docs" / "reference" / "api.md"

PAGE_WEIGHT = 30

# deepLinking stays off: it hijacks window.location.hash for Swagger's own
# routing, which breaks the page's normal anchor navigation wherever a Hextra
# TOC is also present.
PAGE = """---
title: REST API
weight: {weight}
description: "Endpoints, request and response schemas for the agentregistry REST API."
---

<!-- Generated by scripts/generate-api-ref.py from the agentregistry OpenAPI spec.
     Do not edit by hand; the spec is generated upstream by `make gen-openapi` in
     agentregistry-dev/agentregistry. Re-run the reference-docs workflow. -->

The agentregistry server exposes a REST API for managing agents, MCP servers,
skills, prompts, and deployments. The reference below is rendered from the
server's OpenAPI specification.

{{{{< openapi src="ar-docs/openapi.yaml" >}}}}
"""


def main() -> None:
    website_dir = Path(os.environ.get("WEBSITE_DIR", ".")).resolve()
    agentregistry_dir = Path(os.environ.get("AGENTREGISTRY_DIR", "agentregistry")).resolve()

    if not agentregistry_dir.is_dir():
        raise SystemExit(f"Error: agentregistry checkout not found at {agentregistry_dir}")
    if not (website_dir / "hugo.yaml").exists():
        raise SystemExit(f"Error: {website_dir} does not look like the website repo (no hugo.yaml)")

    spec = agentregistry_dir / SPEC_SOURCE
    if not spec.exists():
        raise SystemExit(
            f"Error: {spec} not found. It is generated by `make gen-openapi` in the "
            "product repo and committed there."
        )

    # A spec that parses but is nearly empty would render as a blank Swagger UI
    # with no obvious error, so check it has actual paths before publishing.
    text = spec.read_text(encoding="utf-8")
    if "paths:" not in text:
        raise SystemExit(f"Error: {spec} has no `paths:` section; refusing to publish it.")

    target = website_dir / SPEC_TARGET
    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(spec, target)

    page = website_dir / OUTPUT_PATH
    page.parent.mkdir(parents=True, exist_ok=True)
    page.write_text(PAGE.format(weight=PAGE_WEIGHT), encoding="utf-8")

    kb = target.stat().st_size // 1024
    print(f"  Copied {SPEC_TARGET} ({kb} KB) and generated {OUTPUT_PATH}.")


if __name__ == "__main__":
    main()
