#!/usr/bin/env python3
"""
Generate the arctl CLI reference for the agentregistry website.

Writes a throwaway Go program that imports arctl's exported command tree and
runs cobra's doc generator over it, then rewrites the result into finished Hugo
pages under content/docs/reference/cli/ — front matter and body in one file,
matching how the reference was laid out before it was automated.

The generator program lives here rather than in the product repo so that
publishing docs needs no upstream change, and so cobra/doc's markdown
dependencies stay out of agentregistry's go.mod. It reaches the CLI through a
`replace` directive against a plain checkout; pkg/cli.Root is a documented
public entry point (see that package's README), which is what makes this safe
to depend on from outside the module.

Every page in content/docs/reference/cli/ is generated. Editing one by hand is
pointless: the next run overwrites it. Change the cobra command definitions in
agentregistry-dev/agentregistry instead.

Usage (from the workflow, or locally):
  AGENTREGISTRY_DIR=/path/to/agentregistry \\
  WEBSITE_DIR=/path/to/website \\
  python3 scripts/generate-arctl-ref.py
"""

import os
import re
import subprocess
import tempfile
from pathlib import Path

# The doc generator, written into a temp module at run time.
#
# Three things here are guards, not boilerplate:
#
#   docsEnv       Several persistent flags seed their *default* from the
#                 environment — --registry-url defaults to $ARCTL_API_BASE_URL.
#                 Under the real OSEnv, whatever is exported on the machine
#                 running generation gets baked into the published flag table,
#                 so a runner with a staging registry set would silently commit
#                 that host into the docs.
#
#   Version       version.Version comes from ldflags and varies per build (a tag
#                 in CI, "dev" locally). Cobra prints it on the root page, so
#                 leaving it alone churns the docs for a reason that has nothing
#                 to do with the CLI's surface.
#
#   InitDefault-  Cobra adds the `completion` command and the root's --version
#   *Cmd/Flag     flag lazily inside execute(), so a plain doc run silently omits
#                 both: four shell subcommands and a flag users can actually pass.
GO_DOC_GEN = '''package main

import (
\t"fmt"
\t"log"
\t"os"

\t"github.com/spf13/cobra/doc"

\t"github.com/agentregistry-dev/agentregistry/pkg/cli"
\tcliruntime "github.com/agentregistry-dev/agentregistry/pkg/cli/runtime"
)

type docsEnv struct{}

var _ cliruntime.Env = docsEnv{}

func (docsEnv) Getenv(string) string { return "" }

func main() {
\tif len(os.Args) < 2 {
\t\tfmt.Fprintln(os.Stderr, "usage: gen-arctl-docs <out-dir>")
\t\tos.Exit(1)
\t}

\tcfg := cli.DefaultConfig()
\tcfg.Env = docsEnv{}
\tcfg.Version = "latest"

\troot := cli.Root(cfg)
\troot.InitDefaultCompletionCmd()
\troot.InitDefaultVersionFlag()
\troot.DisableAutoGenTag = true

\tif err := os.MkdirAll(os.Args[1], 0o755); err != nil {
\t\tlog.Fatalf("creating output directory: %v", err)
\t}
\tif err := doc.GenMarkdownTree(root, os.Args[1]); err != nil {
\t\tlog.Fatalf("generating CLI docs: %v", err)
\t}
}
'''

# The generator's own module. `go mod tidy` fills in the rest; only the two
# direct requires and the replace matter here. The Go directive is deliberately
# older than agentregistry's own so this keeps working if that repo moves ahead
# of the runner's toolchain.
GO_MOD_TEMPLATE = '''module gen-arctl-docs

go 1.25

require (
\tgithub.com/agentregistry-dev/agentregistry v0.0.0-00010101000000-000000000000
\tgithub.com/spf13/cobra v1.10.2
)

replace github.com/agentregistry-dev/agentregistry => {agentregistry_path}
'''

# Path relative to the website checkout.
CONTENT_SUBDIR = Path("content") / "docs" / "reference" / "cli"

# Every command page shares one weight. Hextra falls back to sorting equal
# weights by title, and every title starts with "arctl", so the root page
# (shortest title) sorts first and the subcommands alphabetize after it.
PAGE_WEIGHT = 10

# Warns anyone who opens a page in an editor rather than the site.
GENERATED_NOTICE = (
    "<!-- Generated by scripts/generate-arctl-ref.py from the arctl cobra "
    "commands. Do not edit by hand; edit the command definitions in "
    "agentregistry-dev/agentregistry and re-run the reference-docs workflow. -->"
)


def slug_for(filename: str) -> str:
    """arctl_db_migrate_up.md -> arctl-db-migrate-up"""
    return Path(filename).stem.replace("_", "-")


def title_for(filename: str) -> str:
    """arctl_db_migrate_up.md -> arctl db migrate up"""
    return Path(filename).stem.replace("_", " ")


def yaml_quote(value: str) -> str:
    """Quote a scalar for YAML front matter."""
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


# The canonical help line. Cobra emits a per-command "help for delete", which
# says nothing a reader does not already know and differs on every page; the
# reference has always carried one shared wording under Global flags instead.
HELP_FLAG = ("-h", "--help", "Display help information for the command.")

# Prose-only code-span recovery.
#
# The cobra Long strings are Go RAW string literals, and a raw literal is
# delimited by backticks — so a code span cannot be written into one without
# converting every Long to concatenated interpreted strings. That conversion was
# tried and reverted: cobra prints these strings verbatim to the terminal, so
# every backtick added for the docs shows up as literal punctuation in
# `arctl --help`. Terminal readers should not pay for Markdown.
#
# So the formatting is reconstructed here instead. Each pattern is deliberately
# narrow, because a greedy rule silently rewords generated prose that nobody
# reviews. Anything ambiguous is left plain.
CODE_SPAN_PATTERNS = [
    # Long flags: --dry-run, --all-tags. Bounded so "well--formed" is untouched.
    re.compile(r"(?<![\w`-])(--[a-z][a-z0-9-]*)(?![\w`-])"),
    # HTTP method + path: POST /v0/apply
    re.compile(r"(?<![\w`])((?:GET|POST|PUT|PATCH|DELETE) /\S+?)(?=[\s,.;:)]|$)"),
    # Env vars: ARCTL_API_TOKEN. The underscore requirement is what keeps this
    # off bare-caps placeholders such as TYPE, NAME, FILE and YAML.
    re.compile(r"(?<![\w`])([A-Z][A-Z0-9]*(?:_[A-Z0-9]+)+)(?![\w`])"),
    # Filenames: agent.yaml, arctl.yaml, 001_init.down.sql, marketplace.json.
    re.compile(r"(?<![\w`/.])([\w][\w.-]*\.(?:yaml|yml|json|sql|toml|md))(?![\w`])"),
    # Dotfiles, named explicitly. A general "\.[a-z]+" rule looks tempting but
    # claims the ".yaml" of "<name>.yaml" — the char before that dot is ">",
    # so the filename rule above cannot take it first.
    re.compile(r"(?<![\w`./>])(\.(?:env|gitignore|dockerignore))(?![\w`.])"),
    # snake_case identifiers: schema_migrations, pg_advisory_lock.
    re.compile(r"(?<![\w`])([a-z]+(?:_[a-z]+)+)(?![\w`])"),
    # Qualified Go-ish field paths: Spec.Source.Repository.URL
    re.compile(r"(?<![\w`.])([A-Z][A-Za-z0-9]*(?:\.[A-Z][A-Za-z0-9]*){2,})(?![\w`])"),
    # The declarative API group: ar.dev/v1alpha1
    re.compile(r"(?<![\w`/])(ar\.dev/v[0-9a-z]+)(?![\w`])"),
]

# The Long strings quote command names and literals with single quotes, which is
# the plain-text stand-in for a code span: 'arctl init', 'up'. The lookbehind
# keeps it off possessive apostrophes ("the resource's source"), and barring
# apostrophes inside the span stops a match running from one possessive to the
# next.
SINGLE_QUOTED = re.compile(r"(?<![A-Za-z])'([a-z][A-Za-z0-9._-]*(?: [a-z][A-Za-z0-9._-]*){0,2})'")

# Type/kind enumerations. Only the enumeration line itself and an immediately
# following "(... e.g. a, b, c)" parenthetical are rewritten — the bare kind
# names also occur as ordinary nouns ("Run the agent or MCP server"), so
# backticking them document-wide would corrupt normal prose.
ENUM_LINE = re.compile(r"^(Supported (?:types|kinds):|.*?must be one of:)(\s*)(.+)$")
ENUM_EG = re.compile(r"^(\(.*?e\.g\.\s*)(.+?)(\)?)$")


# A leading run of comma-separated identifiers, and nothing after it. The
# enumeration frequently shares its line with the sentence that follows it
# ("Supported types: agent, mcp, skill. Reads the resource's ..."), so matching
# to end-of-line would code-span ordinary prose.
ENUM_ITEMS = re.compile(r"^([A-Za-z][\w-]*(?:,\s*[A-Za-z][\w-]*)*)")


def backtick_list(items: str) -> str:
    """Backtick the leading comma-separated identifier run, leaving any tail."""
    m = ENUM_ITEMS.match(items)
    if not m:
        return items
    listed = re.sub(r"(?<![\w`])([A-Za-z][\w-]*)(?![\w`])", r"`\1`", m.group(1))
    return listed + items[m.end():]


def mark_enumerations(prose: str) -> str:
    """Code-span the members of a "Supported types:" style enumeration."""
    lines = prose.split("\n")
    for i, line in enumerate(lines):
        m = ENUM_LINE.match(line)
        if not m:
            continue
        lines[i] = m.group(1) + m.group(2) + backtick_list(m.group(3))
        if i + 1 < len(lines):
            eg = ENUM_EG.match(lines[i + 1])
            if eg:
                lines[i + 1] = eg.group(1) + backtick_list(eg.group(2)) + eg.group(3)
    return "\n".join(lines)


def placeholders_from_usage(usage: str) -> list[str]:
    """Collect ALL-CAPS argument placeholders from a command's usage line.

    Deriving them from the usage string rather than a hand-kept list means a
    command that renames or adds an argument gets it code-spanned in prose
    automatically — and a caps word that is NOT an argument of this command is
    never touched.
    """
    return sorted({t for t in re.findall(r"\b[A-Z][A-Z0-9]{0,11}\b", usage)}, key=len, reverse=True)


def strip_heading(text: str) -> tuple[str, str]:
    """Drop cobra's leading `## <command>` and return (short, rest).

    The heading goes because the front-matter title already renders as the page
    H1. The line under it is the command's Short.
    """
    without = re.sub(r"^## .+?\n+", "", text, count=1)
    short = ""
    stripped = without.lstrip()
    if stripped and not stripped.startswith(("#", "```")):
        short = stripped.split("\n", 1)[0].strip()
        without = stripped[len(short):]
    return short, without


def take_fence(text: str) -> tuple[str, str]:
    """Pull the first fenced block out of `text`; return (contents, remainder)."""
    m = re.search(r"```[a-z]*\n(.*?)```", text, re.S)
    if not m:
        return "", text
    return m.group(1).strip("\n"), (text[: m.start()] + text[m.end():])


def split_inline_examples(prose: str) -> tuple[str, str]:
    """Separate a trailing `Examples:` block from the Long text.

    Several commands embed their examples in the Long rather than cobra's
    Example field, as a literal "Examples:" line followed by indented commands.
    Left in place those lines are only two spaces deep, which is not enough for
    a Markdown code block, so they get swallowed into the preceding paragraph.
    Pulled out here they become a real fenced block instead.
    """
    m = re.search(r"^Examples?:\s*\n((?:[ \t]+\S.*\n?|[ \t]*\n(?=[ \t]+\S))*)", prose, re.M)
    if not m:
        return prose, ""
    return prose[: m.start()].rstrip(), dedent_block(m.group(1).rstrip())


def dedent_block(block: str) -> str:
    """Remove the common leading indent from every line of a block.

    Cobra indents flag tables by two columns and example blocks by two spaces.
    The reference has always rendered them flush left inside the fence.
    """
    lines = [ln for ln in block.split("\n")]
    widths = [len(ln) - len(ln.lstrip()) for ln in lines if ln.strip()]
    if not widths:
        return block
    cut = min(widths)
    return "\n".join(ln[cut:] if ln.strip() else "" for ln in lines)


def parse_flags(block: str) -> list[tuple[str, str, str]]:
    """Split a cobra flag table into (shorthand, name, description) triples.

    A flag line is a spec and a description separated by two or more spaces,
    where the spec may or may not lead with a single-letter shorthand:

        -f, --filename string   YAML file to read resources from
            --all-tags          Delete every tag of NAME

    The three parts are kept separate rather than as one spec string because
    the shorthand occupies its own column. Splitting it out is what lets
    render_flags re-align a table after -h has been moved between sections,
    which otherwise collapses the indent that keeps `--all-tags` under the
    `--filename` of the line above.

    Anything not matching that shape is passed through as a name with no
    description, so an unexpected line survives instead of being dropped.
    """
    triples: list[tuple[str, str, str]] = []
    for line in block.split("\n"):
        if not line.strip():
            continue
        m = re.match(r"^\s*(.*?\S)\s{2,}(\S.*)$", line)
        spec, desc = (m.group(1), m.group(2)) if m else (line.strip(), "")
        sm = re.match(r"^(-[A-Za-z]), (--.*)$", spec)
        triples.append((sm.group(1), sm.group(2), desc) if sm else ("", spec, desc))
    return triples


def render_flags(triples: list[tuple[str, str, str]]) -> str:
    """Re-align a flag table: shorthand column, then names, then descriptions."""
    if not triples:
        return ""
    width = max(len(name) for _, name, _ in triples)
    lines = []
    for short, name, desc in triples:
        prefix = f"{short}, " if short else "    "
        body = f"{name.ljust(width)}   {desc}" if desc else name
        lines.append((prefix + body).rstrip())
    return "\n".join(lines)


def fence_indented_runs(prose: str) -> str:
    """Turn runs of indented lines in the Long into fenced sh blocks.

    Cobra Long strings indent example invocations by two spaces. Two spaces is
    not enough to make a Markdown code block, so those lines are absorbed as
    lazy continuations of the paragraph above them and render as prose — e.g.
    "...sends DELETE /v0/apply. arctl delete -f agent.yaml" run together on one
    line. Fencing each run keeps them readable and, because add_code_spans
    skips fenced content, also stops the flags inside them being backticked.
    """
    out: list[str] = []
    run: list[str] = []

    def flush() -> None:
        # A run of "- item" / "1. item" lines is a Markdown list that a two-space
        # indent renders correctly on its own. Fencing it would turn a bulleted
        # list of generated files into a shell snippet.
        if run and all(re.match(r"\s*([-*+]|\d+\.)\s", ln) for ln in run):
            out.extend(ln.strip() for ln in run)
            run.clear()
            return
        if run:
            # Blank line first: a fence glued to the paragraph above it renders,
            # but reads as a continuation in the source and in Copy-as-Markdown.
            if out and out[-1].strip():
                out.append("")
            out.append("```sh\n" + dedent_block("\n".join(run)) + "\n```")
            run.clear()

    for line in prose.split("\n"):
        if line.startswith((" ", "\t")) and line.strip():
            run.append(line)
        elif not line.strip() and run:
            # A blank line inside an indented run keeps the run open only if
            # the next line is indented too; simplest correct call is to close.
            flush()
            out.append("")
        else:
            flush()
            out.append(line)
    flush()
    return "\n".join(out)


def add_code_spans(prose: str, placeholders: list[str] | None = None) -> str:
    """Wrap high-confidence tokens in backticks, skipping fenced/inline code."""
    parts = re.split(r"(```.*?```|`[^`]*`)", prose, flags=re.S)
    for i, part in enumerate(parts):
        if part.startswith("`"):
            continue
        part = mark_enumerations(part)
        part = SINGLE_QUOTED.sub(lambda m: f"`{m.group(1)}`", part)
        for pattern in CODE_SPAN_PATTERNS:
            part = pattern.sub(lambda m: f"`{m.group(1)}`", part)
        for token in placeholders or []:
            part = re.sub(rf"(?<![\w`]){re.escape(token)}(?![\w`])", f"`{token}`", part)
        parts[i] = part
    return "".join(parts)


def demote_prose_headings(prose: str) -> str:
    """Turn headings inside a Long into bold labels.

    Cobra's own built-in completion help ships `#### Linux:` / `#### macOS:` in
    its Long text. Those are sub-labels of a sentence, not page sections, but
    Hextra puts every heading in the right-rail TOC — so each of the four
    completion pages listed "Linux:" and "macOS:" ABOVE its own "Usage" entry.
    They are also a heading-level skip, since nothing above them is an H2 or H3.

    Bold keeps them visible and correctly subordinate without inventing TOC
    entries. Applied to prose only, so the section headings this script emits
    are unaffected.
    """
    return re.sub(r"^#{1,6}\s*(.+?)\s*$", r"**\1**", prose, flags=re.M)


def escape_angle_tokens(text: str) -> str:
    """Entity-escape `<name>`-style placeholders outside code spans and fences.

    Goldmark runs with `unsafe: true` on this site, so a bare <name> in prose is
    parsed as an HTML tag and disappears from the rendered page. The same token
    in a front-matter description is worse: extras' page-description partial
    pipes the value through `markdownify | plainify`, which renders the token as
    a tag and then strips it, so `arctl init prompt`'s description published as
    "Create a new declarative .yaml for a prompt." — silently missing the word
    it was describing.

    Escaping to entities round-trips correctly: `plainify` leaves them alone and
    the partial's closing `htmlUnescape` restores the literal angle brackets.
    """
    parts = re.split(r"(```.*?```|`[^`]*`)", text, flags=re.S)
    for i, part in enumerate(parts):
        if part.startswith("`"):
            continue
        parts[i] = re.sub(
            r"<([a-zA-Z][A-Za-z0-9_-]*)>", r"&lt;\1&gt;", part
        )
    return "".join(parts)


def rewrite_links(text: str) -> str:
    """Point cobra's relative .md cross-links at the published page URLs.

    Cobra emits [arctl db migrate](arctl_db_migrate.md). The pages are siblings
    under /docs/reference/cli/, so ../<slug>/ resolves correctly from any of
    them.

    The character class has to allow hyphens: a command whose own name contains
    one produces a mixed filename like arctl_configure_claude-code.md, and a
    [A-Za-z0-9_]-only pattern silently leaves those links pointing at a .md file
    that the site never publishes.
    """

    def sub(match: re.Match) -> str:
        return f"[{match.group(1)}](../{slug_for(match.group(2))}/)"

    return re.sub(r"\[([^\]]+)\]\(([A-Za-z0-9_-]+\.md)\)", sub, text)


def build_page(raw: str) -> tuple[str, str]:
    """Turn one cobra file into (description, body) in the reference's own shape.

    Cobra's layout is man-page shaped: Short, Synopsis, a bare usage fence,
    Options, Options inherited from parent commands, SEE ALSO. The reference
    reads as a task doc instead — prose, Usage, Command-specific flags, Global
    flags — so the sections are re-emitted rather than just renamed. Nothing is
    dropped; SEE ALSO is the only section that keeps its position.
    """
    short, rest = strip_heading(raw)

    # Cobra writes each section as `### <name>`; split on those.
    chunks = re.split(r"^### (.+)$", rest, flags=re.M)
    lead, sections = chunks[0], dict(zip(chunks[1::2], chunks[2::2]))

    # The usage fence sits at the end of Synopsis, or in the lead when the
    # command sets no Long.
    synopsis = sections.get("Synopsis", "")
    usage, synopsis = take_fence(synopsis)
    if not usage:
        usage, lead = take_fence(lead)

    prose, inline_examples = split_inline_examples(synopsis.strip() or "")
    examples, _ = take_fence(sections.get("Examples", ""))
    examples = dedent_block(examples) if examples else inline_examples

    # Fall back to the Short when the command sets no Long, so a bare parent
    # command still says what it is.
    body_prose = escape_angle_tokens(add_code_spans(
            demote_prose_headings(fence_indented_runs(prose.strip() or short)),
            placeholders_from_usage(usage),
        ))

    # Both flag tables arrive wrapped in their own fence; parse the contents,
    # not the fence markers.
    own_flags, _ = take_fence(sections.get("Options", ""))
    inherited_flags, _ = take_fence(sections.get("Options inherited from parent commands", ""))

    flags = [t for t in parse_flags(own_flags) if t[1] != "--help"]
    inherited = parse_flags(inherited_flags)

    # The root command has no parent, so cobra files its persistent flags
    # (--registry-url, --registry-token) under Options rather than under
    # "inherited". Those are precisely the flags every subcommand shows as
    # global, so listing them as command-specific on the root page contradicts
    # all 31 other pages. Absence of an inherited section identifies the root.
    if not inherited:
        flags, inherited = [], flags

    out = [body_prose]
    if usage:
        out.append(f"## Usage\n\n```sh\n{usage}\n```")
        if examples:
            out.append(f"Examples:\n\n```sh\n{examples}\n```")
    elif examples:
        out.append(f"## Usage\n\n```sh\n{examples}\n```")
    if flags:
        out.append(f"## Command-specific flags\n\n```sh\n{render_flags(flags)}\n```")
    # -h is on every command, so it belongs with the other always-present flags.
    out.append(
        "## Global flags\n\n```sh\n"
        + render_flags([HELP_FLAG] + inherited)
        + "\n```"
    )
    if "SEE ALSO" in sections:
        out.append("## See also\n\n" + rewrite_links(sections["SEE ALSO"]).strip())

    description = escape_angle_tokens(short.rstrip())
    if description and description[-1] not in ".!?":
        description += "."

    return description, "\n\n".join(s.strip() for s in out if s.strip()) + "\n"


def clear_stale(directory: Path, keep: set[str]) -> None:
    """Delete arctl-*.md pages the current run did not produce.

    Without this, renaming or removing a command leaves its page published
    forever. _index.md is hand-maintained and never touched.
    """
    for existing in sorted(directory.glob("arctl*.md")):
        if existing.name not in keep:
            existing.unlink()
            print(f"    - Removed stale {existing.name}")


def run_generator(agentregistry_dir: Path, gen_dir: Path, out_dir: Path) -> None:
    """Build and run the doc generator against a plain agentregistry checkout."""
    module_root = agentregistry_dir
    if not (module_root / "go.mod").exists():
        raise SystemExit(
            f"Error: no go.mod under {module_root}. "
            "AGENTREGISTRY_DIR must point at an agentregistry checkout."
        )

    gen_dir.mkdir(parents=True, exist_ok=True)
    (gen_dir / "main.go").write_text(GO_DOC_GEN, encoding="utf-8")
    (gen_dir / "go.mod").write_text(
        GO_MOD_TEMPLATE.format(agentregistry_path=module_root.resolve()),
        encoding="utf-8",
    )

    # Resolve cobra/doc and its markdown dependencies into the generator's own
    # go.sum. This is the whole reason the program lives in a temp module: those
    # deps never touch agentregistry's go.mod.
    subprocess.run(["go", "mod", "tidy"], check=True, cwd=gen_dir)
    subprocess.run(["go", "run", ".", str(out_dir)], check=True, cwd=gen_dir)


def generate(website_dir: Path, agentregistry_dir: Path) -> None:
    content_dir = website_dir / CONTENT_SUBDIR
    content_dir.mkdir(parents=True, exist_ok=True)

    with tempfile.TemporaryDirectory() as tmp:
        raw_dir = Path(tmp) / "raw"
        run_generator(agentregistry_dir, Path(tmp) / "gen", raw_dir)

        produced: set[str] = set()
        for src in sorted(raw_dir.glob("*.md")):
            slug = slug_for(src.name)
            title = title_for(src.name)
            description, body = build_page(src.read_text(encoding="utf-8"))
            description = description or f"Reference for the {title} command."
            (content_dir / f"{slug}.md").write_text(
                "---\n"
                f"title: {title}\n"
                f"weight: {PAGE_WEIGHT}\n"
                f"description: {yaml_quote(description)}\n"
                "---\n\n"
                f"{GENERATED_NOTICE}\n\n"
                f"{body.strip()}\n",
                encoding="utf-8",
            )
            produced.add(f"{slug}.md")
            print(f"    + {slug}")

        clear_stale(content_dir, produced)

    print(f"  Generated {len(produced)} arctl command pages.")


def main() -> None:
    website_dir = Path(os.environ.get("WEBSITE_DIR", ".")).resolve()
    agentregistry_dir = Path(os.environ.get("AGENTREGISTRY_DIR", "agentregistry")).resolve()

    if not agentregistry_dir.is_dir():
        raise SystemExit(f"Error: agentregistry checkout not found at {agentregistry_dir}")
    if not (website_dir / "hugo.yaml").exists():
        raise SystemExit(f"Error: {website_dir} does not look like the website repo (no hugo.yaml)")

    generate(website_dir, agentregistry_dir)


if __name__ == "__main__":
    main()
