#!/usr/bin/env python3
"""
Generate the Helm values reference for the agentregistry website.

Runs helm-docs against a checkout of the product repo's chart and writes the
values table to content/docs/reference/helm.md.

Only the values table is published, not the chart's whole README. The README is
written for people browsing the chart repo — it opens with a TL;DR install
one-liner and closes with Maintainers and Source Code — and its install,
database and RBAC narrative would compete with the site's own setup guides.
The values table is the part that is generated from values.yaml, so it is the
part that silently drifts, and it is what a reference page is for.

helm-docs is driven with our own single-line template (scripts/helm-values.gotmpl)
rather than by slicing the "## Parameters" section out of the rendered README.
Slicing would couple this script to a heading in a template it does not own —
rename that heading upstream and the extraction returns nothing, quietly.

Usage (from the workflow, or locally):
  AGENTREGISTRY_DIR=/path/to/agentregistry \\
  WEBSITE_DIR=/path/to/website \\
  python3 scripts/generate-helm-ref.py
"""

import os
import re
import subprocess
from pathlib import Path

OUTPUT_PATH = Path("content") / "docs" / "reference" / "helm.md"
TEMPLATE = Path("scripts") / "helm-values.gotmpl"

PAGE_WEIGHT = 20

FRONT_MATTER = """---
title: Helm values
weight: {weight}
description: "Configuration values for the agentregistry Helm chart."
---

<!-- Generated by scripts/generate-helm-ref.py from the agentregistry Helm chart's
     values.yaml. Do not edit by hand; edit values.yaml in
     agentregistry-dev/agentregistry and re-run the reference-docs workflow. -->

Every value the agentregistry Helm chart accepts, with its type and default.
Override them with `--set key=value` on the install command, or by passing a
values file with `-f`.

"""


def render_values(agentregistry_dir: Path, template: Path) -> str:
    """Run helm-docs against the chart and return the rendered values table."""
    chart_dir = agentregistry_dir / "charts" / "agentregistry"
    if not (chart_dir / "values.yaml").exists():
        raise SystemExit(f"Error: no chart found at {chart_dir}")

    # helm-docs needs a Chart.yaml, which this repo generates from
    # Chart-template.yaml and gitignores. Use the product repo's own target so
    # the version substitution stays whatever upstream says it is.
    subprocess.run(["make", "charts-generate"], check=True, cwd=agentregistry_dir)

    # Run the helm-docs pinned in the product repo's tools module rather than
    # whatever happens to be on PATH, so the table's formatting cannot change
    # under us between runs.
    result = subprocess.run(
        [
            "go", "tool", "-modfile=tools/go.mod", "helm-docs",
            "--log-level=fatal",
            "-c", "./charts/agentregistry",
            f"--template-files={template.resolve()}",
            "--dry-run",
        ],
        check=True,
        cwd=agentregistry_dir,
        capture_output=True,
        text=True,
    )
    return result.stdout


def clean(values: str) -> str:
    """Drop helm-docs' own heading and normalize trailing whitespace.

    The `## Values` heading is dropped because the front-matter title already
    names the page; keeping it would put a lone redundant entry in the TOC.
    """
    values = re.sub(r"^##+ Values\s*\n+", "", values, count=1)
    return values.strip() + "\n"


def check_table(values: str) -> None:
    """Fail loudly if the render is empty or not a table.

    A silent empty render is the failure mode worth guarding: helm-docs exits 0
    when a template produces nothing, so without this the workflow would happily
    open a PR deleting every documented value.
    """
    rows = [ln for ln in values.split("\n") if ln.startswith("|")]
    if len(rows) < 3:
        raise SystemExit(
            f"Error: helm-docs produced {len(rows)} table rows, expected a full "
            "values table. Check scripts/helm-values.gotmpl against the "
            "helm-docs version pinned in the product repo."
        )
    # Header, separator, and one row per value; every row needs 4 columns.
    bad = [r for r in rows if r.count("|") != 5]
    if bad:
        raise SystemExit(
            f"Error: {len(bad)} malformed table row(s), first: {bad[0][:120]}"
        )


def main() -> None:
    website_dir = Path(os.environ.get("WEBSITE_DIR", ".")).resolve()
    agentregistry_dir = Path(os.environ.get("AGENTREGISTRY_DIR", "agentregistry")).resolve()

    if not agentregistry_dir.is_dir():
        raise SystemExit(f"Error: agentregistry checkout not found at {agentregistry_dir}")
    if not (website_dir / "hugo.yaml").exists():
        raise SystemExit(f"Error: {website_dir} does not look like the website repo (no hugo.yaml)")

    values = clean(render_values(agentregistry_dir, website_dir / TEMPLATE))
    check_table(values)

    target = website_dir / OUTPUT_PATH
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(FRONT_MATTER.format(weight=PAGE_WEIGHT) + values, encoding="utf-8")

    rows = sum(1 for ln in values.split("\n") if ln.startswith("|")) - 2
    print(f"  Generated {OUTPUT_PATH} ({rows} values).")


if __name__ == "__main__":
    main()
